# Generated by Django 4.1 on 2022-11-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='features',
            new_name='Feature',
        ),
    ]
